# Generated by Django 3.0.9 on 2020-09-04 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canairio_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanairioStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=24, unique=True)),
                ('firmware_version', models.CharField(max_length=12)),
                ('time_stamp', models.DateTimeField()),
                ('gps_coords', models.CharField(max_length=24)),
                ('country_state_code', models.CharField(max_length=12)),
                ('city_name', models.CharField(max_length=24)),
                ('neighborhood_name', models.CharField(max_length=24)),
                ('zip_code', models.CharField(max_length=12)),
                ('station_id', models.CharField(max_length=12, unique=True)),
                ('used_in', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('canairio_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canairio_user.CanairioUser')),
            ],
        ),
    ]
